### ISSUE TITLE
Not found Firefox addon

### ISSUE THREAD

**Issue by ybiquitous** [eps1lon/dependabot-clickable-commands#2]
I notice that the link to the Firefox Addon page in the README points to "404 Not Found".

- https://addons.mozilla.org/en-US/developers/addon/3e8d7402d45c4033a399
- https://github.com/eps1lon/dependabot-clickable-commands/blob/master/README.md#install

<img width="1579" alt="image" src="https://user-images.githubusercontent.com/473530/63233806-3355de00-c26d-11e9-9cf7-53b7a590f5f9.png">
 
I would be very happy if you could fix it. 😃

**Comment by eps1lon** [comment]
For some reasons it's not public. Though I can't find anything on google why that is (the addon was approved). The docs do not say anything about private vs public addons. I won't spend hours searching for this documentation. If somebody can point me to the relevant docs I'd appreciate it.

**Comment by ybiquitous** [comment]
It's sad 😢 Perhaps nobody may knows the reasons.

Please feel free to close this issue.

**Comment by eps1lon** [comment]
I'm leaving this open in case someone can explain it to me.

Does the `.xpi` help? This is uploaded with the github release e.g. https://github.com/eps1lon/dependabot-clickable-commands/releases/tag/v0.3.0

**Comment by ybiquitous** [comment]
Oh, thank you! The `.xpi` help me! 👍

**Comment by ybiquitous** [comment]
I start watching the repo's release just now, so I will not have a problem for a while. 👍

**Comment by eps1lon** [comment]
Available starting with 0.3.3: https://addons.mozilla.org/en-US/firefox/addon/clickable-dependabot-commands/. Just submitted 0.3.4.
